### PR TITLE
Property "name" split into Given and Family name

### LINKED ISSUE #1: Name needs "giveName" and "familyName"
Hi, 
from our experience and also a lot of opinions from colleagues the property "name" should be split into "givenName" and "familyName". All known (travel-) documents (passports, id-cards ...) work this way. The information in the cerificate is also needed to be checked against a travel document.

If a reference to e.g. HL7 is needed, 2.24.2.12 HumanName can be used, viz. https://www.hl7.org/fhir/datatypes.html#humanname

e.g.

           "properties": {
                "gn": {
                    "title": "Given name",
                    "description": "The given name/s of the person addressed in the certificate",
                    "type": "string",
                    "example": "Tolvan"
                },
                "fn": {
                    "title": "Family name",
                    "description": "The family name/s of the person addressed in the certificate",
                    "type": "string",
                    "example": "Tolvansson"
                },

Thanks

### PR DESCRIPTION
**Pull request by chris2286266**
closes #1

### CODE REVIEW

**Comment by jschlyter** [comment]
Would it be possible to allow for either `n` or `gn`/`fn` as a compromise?


```
anyOf:
  - required:
    - n
  - required:
    - fn
    - gn
```

**Comment by chris2286266** [comment]
IMHO Yes.

**Comment by jschlyter** [comment]
@chris2286266 why add a new file? I suggest we just keep adding to v1 for now.

**Comment by jschlyter** [comment]
Why do you want to add any certificate metadata to the hcert payload? As this information is bound to the key, it is part of the trusted list metadata - not the payload itself. IMHO, there's no reason for having take up vital information in the payload.

Please elaborate so we can better understand the use.

**Comment by chris2286266** [comment]
> Why do you want to add any certificate metadata to the hcert payload? As this information is bound to the key, it is part of the trusted list metadata - not the payload itself. IMHO, there's no reason for having take up vital information in the payload.
> 
> Please elaborate so we can better understand the use.

Sorry for my probably inaccurate wording,

I of course meant the meta data of the health certificate, not of the signature certificate!

The requirements to integrate this meta information into the "hcert" come from the eHN guidelines. Viz. e.g. https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf

Regards,
Chris

**Comment by jschlyter** [comment]
@chris2286266 all good, my cryptoself triggered on the word "metadata" and "expire". No worries!

**Comment by dirkx** [comment]
I think we are talking the eHealth digital green metadata -- not the X.509 like data on the key.

**Comment by chris2286266** [comment]
As I am not aware of the "rules" within this team: who will/shall ... merge the PR?
Can/shall I do it?
Or does someone have to confirm it?

**Pull request merged**
